* fundamentos de electronica
** glosario
+ q: carga
+ i: corriente
+ t: tiempo
+ v: voltaje
+ p: poder
+ w: energia
+ R: resistencia
+ G: conductancia
+ Coulombs: las cargas electricas se miden en Coulombs (C)
+ Amperios: corriente electrica se mide en Amperios (A)
+ volts: la energia necesaria para poder mover cargas entre puntos (V)
+ watts: es el ratio de energia consumida o absorbida (W)
+ Joules: es la capacidad de hacer trabajo
+ Corriente constante: la corriente constante se representa con (I)
+ Corriente variante: la corriente varia se representa con (i)
+ ohmios: unidad que representa la capacidad de oponerse a la corriente de un material($\Omega$)
+ siemens: unidad de medida que representa la capacidad de un material para permitir el flujo de corriente(S)

** que son las cargas electricas?
la materia se puede cargar electricamente almacenando electrones donde cada electron equivale a: $-1.602e-19C$

** que es la corriente?
la corriente el movimiento de las cargas electricas. ya que una cualidad
de las cargas electricas es que osn moviles y se rigen por la ley de la conservacion de la energia
la formula para calcularla es:    $i=\frac{dq}{dt}$

** Que es el votaje?
el voltaje es la energia por carga que se necesita para poder mover electrones de un punto a otro esta se mida en volts(V).
los volts en circuitos nos ayudan a ver la diferencia de voltaje entre un punto y otro generalmente alrededor de elemtos
donde tendremos un punto con el simbolo + punto a y otro con el simbolo - punto b donde volts se puede interpretar como
el punto a tiene una bajada de xV con respecto al punto b o viceversa el punto b presenta una subida de xV con
respecto al punto a. para calcular voltaje se tiene la formula: $V_{ab}=\frac{dw}{dq}$ 

** Que es el poder?
el poder es el gasto de energia o su absorcion se mide en watts(w) para diferencias si un elemento absorbe energia o si este la
produce se tiene el signo + y - donde +p quiere decir que absorbe la energia mientras -p quiere decir que esta saliendo energia
del elemento. el poder se calcula con la formula: $p=vi$ y para calcular la absorcion o produccion de energia en un intervalo
se usa la formula $\int_{t_0}^{t_1} vidt$

** Tipos de corriente
existen 2 tipos de corriente corriente directa (DC) conrriente alterna (AC)
 la corriente directa no varia con el tiempo y solo fluye en una direccion
mientras que la corriente alterna puede fluir en ambas direcciones

** elementos activos del circuito
los elementos activos a son aquellos que producen energia son baterias, generadores o amplicadores operacionales los llamamos fuentes
hay 2 tipos de fuentes las dependientes e independientes
- independientes: son aquellas que producen la corriente o voltaje para alimentar los elementos conectados a estos independientemente
  de el voltaje o corriente en el circuito son representados por 2 lineas una grande y una chica o con circulos con polaridad.
- dependientes: los dependientes tambien producen tanto corriente o voltaje pero la produccion no esta fija es dependiente de una
  variable similar a una funcion matematica un ejemplo podria ser $i=10iA$ donde la produccion esta fijada a la corriente del
  algun lugar del circuito.

** conexiones en paralelo
cuando un elemento se conecta en paralelo y comparten 2 *nodos* entonces tiene el mismo voltaje que su conector las conexiones en paralelo son aquellas
que tienen los terminales positivos y negativos conectados entre si
*** resistencias en paralelo / divisores de corriente
las resistencias en paralelo son llamadas tambien *divisores de corriente* la forma la forma de calcular la resistencia equivalente para asi poder simplificar el
circuito es con la formula $R_{eq}=\frac{R1R2}{R_1+R_2}$ pero lo usual es calcularla usando G entonces usamos esta formula $G_{eq}=G_1+G_2+..+G_n$  para calcular
la corriente se usa la formula $i_n=\frac{G_n}{G_1+G_2+...+G_N}i$

** conexiones en serie
las conexiones en serie son aquellas que conectan un terminal a su opuesto entre elementos
los elementos conectados en serie si comparten exclusivamente un *nodo* entonces van a compartir corriente.
*** resistencias en serie / divisores de voltaje
las resistencias en serie tambien son denominadas como divisores de voltaje esto debido a que la corriente que pase a travez de estas mismas vera si voltaje dividido
entre las resistencias como lo indica la su formula: $v_n=\frac{R_n}{R_1 + R_2 + ... + R_N}v$ tambien nos ayuda a simplificar un circuito sumando todas las resistencias que esten en
serie para obtener su resistencia equivalente y poder remplazarla en el circuito $R_{eq}=R_1 + R_2 + ... + R_n$ asi podiendo reducir N resistencias a solo 1 con el valor
de la resistencia equivalente.
principio del divisor de voltaje: entre mas grande la resistencia mas grande la caida del voltaje

** que es la resistencia?
la resistencia(R) es la capacidad de los materiales de oponerse a el flujo de corriente este varia segun el area del grosor su larga y la resistibilidad del material
esta se calcula con la formula $R=\rho\frac{\ell}{A}$ 

** ley de ohm
la ley de ohm indica que el votaje alrededor de una resistencia es proporcinal a la corriente que fluye por el resistor teniendo esta formula $v=iR$
podemos deducir con esta formula la resistencia(R) siendo $R=v/i$.
la ley de ohm tambien dice que dependiendo de el flujo de la corriente en la polaridad es que se toma valor negativo o positivo en el calculo.
la resitencia puede tambien tomar valores de 0 a $\infty$ siendo que si un elemento tiene un valor de resistencia 0 entonces se dice que es un *corto circuito*
mientras que si toma un valor a infinito $\infty$ entonces se dice que es un *cirtcuito abierto*.
el poder que es disipado por un resistor tambien puede ser expresado en terminos de R $p=vi=i^2R=\frac{v^2}{R}$.

** que es la conductacia?
la conductancia(G) es el reciproco de la resistencia es otra forma de representarla, significa la facilidad de los materiales que tienen para permitir el flujo de
corriente atravez de ellos se calcula de la siguiente forma: $G=\frac{1}{R}$ 
el poder que es disipado por un resistor tambien puede ser expresado en terminos de G $p=vi=v^2G=\frac{i^2}{G}$

** tipos de resistencias
existen 2 tipos de resitencias las variables y las fijas con estos nos referimos a resistencias por la cuales su valor de resistibilidad varia o es fijo
las fijas son las que normalmente se ven o se usan en electronica basica mientras que las variables son multimetros.
algunas resisntecias pueden no respetar la ley de ohm las que lo respetan son llamas *resistencias lineales* su funcion se ve como una funcion lineal y esto se debe
a que la resistiblidad de las resistencias no varia con la corriente.
mientras que las resistencias que no la cumplen son las *resistencias no lineas* su funcion no es linea y esto se debe a que la resisntencia cambia con la corriente
un ejemplo de resistencias no lineales son los diodos.
en la practica todas las resistencias se pueden llegar a comportar como una resistencia *no lineal* bajo ciertas condiones

** nodos, ramas y loops
- ramas: las ramas son los elementos en el circuito
- nodos: son los puntos de 2 o mas ramas
- loops: las rutas entre nodos por las cuales solo es posible llegar pasando como maximo por un nodo mas.
  existen 2 tipos de loops independientes y dependientes los independientes son aquellos que tienen una rama que no es miembro de otro loop

para saber saber si esta esta bien esquematizado un circuito tenemos esta formual $b=l+n-1$ donde b son las ramas, n los nodos y l los loops independientes

** las leyes de kirchoff
las leyes de kirchoff son referentes a el voltaje o a la corriente una ley por cada una de estas
- kcl: la ley de la corriente de kirchoff nos dice que en un nodo o seccion seleccionada la suma de las corrientes debe ser igual a 0 o la suma de las corrientes
  que entran tiene que ser igua a la suma de las corrientes que salen.
  tambien dicta que un circuito no puede tener 2 fuentes de corriente $i$ conectadas en serie a menos que sean iguales $i_1=i_2$ de otra forma se viola la la ley de kirchoff
- kvl: la ley del voltae de kirchoff nos dice que en una ruta cerrada la suma de los voltajes debe ser igual a 0 o igual a los voltajes de signo contrario.
  para tomar el signo de los voltajes se toma en cuenta la polaridad por la que entramos podemos ir tanto a favor de manesillas del reloj como encontra el resultado
  es el mismo en ambos casos pero con signos diferentes.
  tambien dicta que un circuito no puede tener 2 fuentes de voltaje $v$ conectadas en paralelo a menos que estas sean iguales $v_1=v_2$
en general estas leyes nos sirven para poder simplificar tanto fuentes de voltaje como fuentes de corriente combinandolas tras realizar el calculo

** analisis nodal
nos sirve para poder calcular el voltaje de nodos especificos para esto necesitamos declarar un /nodo referencia/ este tendra la numeracion 0 y es de donde nos basaremos
para realizar y enumerar los demas nodos donde se veran numeras de la forma $n - 1$ donde n es el numero de nodos, el analisis nodal consiste de algunos pasos los cuales
son:
- aplicamos la ley de la corriente de kirchoff (kcl) en los nodos 
- una vez indentificamos todas la corrientes que cruzan por nuestros /nodos no referencia/ entonces aplicamos las siguiente formula para el calculo del voltaje
 $i_n=\frac{v_{alto}-v_{bajo}}{R}$ 
- una vez aplicamos las formulas en nuestra kcl usando el metodo que queramos por ejemplo regla de cramer para poder obtener los voltajes de cada nodo

** observaciones
podemos obtener un valor integrando una formula y viceversa me explico queremos calcular carga(q) pero solo tenemos la funcion de la corriente(i)
si derivamos corriente obtendremos q por lo siguiente:
$i=\frac{dq}{dt}$ entonces si integramos esto obtendremos $q=\int{idt}$ 

** dudas:
- ¿que conlleva que la corriente cambie su direccion?
- ¿si se rige por la conservacion de la energia entonces en un sistema obvio cerrado no hay cambios en las cargas? ¿entonces no hay perdidas de energia?
