* fundamentos de electronica sesion 1 pagina 4 - 8 

** glosario 
+ Coulombs: las cargas electricas se miden en Coulombs (C)
+ Amperios: corriente electrica se mide en Amperios (A)
+ Corriente constante: la corriente constante se representa con (I)
+ Corriente variante: la corriente varia se representa con (i)

** que son las cargas electricas?
la materia se puede cargar electricamente almacenando electrones donde cada electron equivale a:   $-1.602e-19C$

** que es la corriente?
la corriente el movimiento de lasc argas electricas. ya que una cualidad
de las cargas electricas es que osn moviles y se rigen por la ley de la conservacion de la energia

duda: ¿si se rige por la conservacion de la energia entonces en un sistema obvio cerrado no hay cambios en las cargas? ¿entonces no hay perdidas de energia?

** Tipos de corriente
existen 2 tipos de corriente corriente directa (DC) conrriente alterna (AC)
la corriente directa no varia con el tiempo y solo fluye en una direccion
mientras que la corriente alterna puede fluir en ambas direcciones

duda: ¿que conlleva que la corriente cambie su direccion?

** problemas
+ cuanta carga representan 4600 electrones?
  $4600*(-1.602e-19)=-7.3692e-16C$
+ cuanta carga representan 6.667 billones de protones?
  $6.667e-9*(1.602e-19)=1.0680534e-9C$
